linters-settings:
  govet:
    check-shadowing: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - govet
    - gosec

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosimple
        - ineffassign
        - staticcheck
        - typecheck
        - unused
        - govet
        - gosec
