name: tests
on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Test Fox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '>=1.24' ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false

      - name: Check out code
        uses: actions/checkout@v4

      - name: Run tests
        run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Run data races tests
        run: go test -v -race -run "TestDataRace|TestRaceHostnamePathSwitch" -count=10 ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
  lint:
    name: Lint Fox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '>=1.24' ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false

      - name: Check out code
        uses: actions/checkout@v4

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
